### ISSUE TITLE
Isolated option

### ISSUE THREAD

**Issue by You2s** [TheDragonCode/laravel-migration-actions#104]
### Feature description

Hello,

First of all, thank you for this bookshop, it is really useful. I would like to know if it was possible to add the isolated option to this package in the same way as [laravel migration](https://laravel.com/docs/9.x/migrations#running-migrations) which allows launching the migration on a single server during a deployment on several servers.

Thanks in advance

**Comment by andrey-helldar** [comment]
Agree. The option is useful. I will do it soon. Thank you.

**Comment by andrey-helldar** [comment]
@You2s, hello!

This functionality is released in version [3.2.0](https://github.com/TheDragonCode/laravel-migration-actions/releases/tag/v3.2.0).

Thank you for your suggestion!
