### ISSUE TITLE
Anonymous migrations do not work with Laravel 8

### ISSUE THREAD

**Issue by zaalbarxx** [TheDragonCode/laravel-migration-actions#37]
- Laravel Actions Version: 2.4.0
- Laravel/Lumen Version: 8.64
- PHP Version: 7.4
- Database: `mysql`
- Database Version: 8

### Description:
Currently the detection of the anonymous migrations feature is not ideal since anonymous migrations has been introduced in Laravel [8.37](https://laravel-news.com/laravel-anonymous-migrations) and the code checks if the major version of the app is 9.

### Steps To Reproduce:
Create Laravel >8.37 project, create anonymous migration and try to migrate. It will fail.

**Comment by andrey-helldar** [comment]
I agree. In the near future I will add the definition of a minor version of the framework.

**Comment by andrey-helldar** [comment]
Released: [v2.5.0](https://github.com/TheDragonCode/laravel-migration-actions/releases/tag/v2.5.0)

**Comment by andrey-helldar** [comment]
Released: [v2.5.0](https://github.com/TheDragonCode/laravel-migration-actions/releases/tag/v2.5.0)

Thank you
